# Generated by Django 5.0.6 on 2024-09-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='defaultdays',
        ),
        migrations.AddField(
            model_name='leave',
            name='remainingdays',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Leave days per year counter'),
        ),
    ]
