# Generated by Django 5.0.6 on 2024-09-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_remove_leave_defaultdays_leave_remainingdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='remainingdays',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
