# Generated by Django 5.0.6 on 2024-09-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_leave_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='leave_balance',
            field=models.PositiveIntegerField(default=160),
        ),
    ]
